language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - build-tools-28.0.3
    - android-28

    # Update Android SDK Tools
    - tools

branches:
  except:
    - gh-pages

notifications:
  email: false
